-- AlterTable
ALTER TABLE "Plan" ADD COLUMN "priceMonthly" DECIMAL(10,2),
ADD COLUMN "priceYearly" DECIMAL(10,2),
ADD COLUMN "priceOneTime" DECIMAL(10,2),
ADD COLUMN "currency" TEXT NOT NULL DEFAULT 'TRY',
ADD COLUMN "taxRatePct" INTEGER NOT NULL DEFAULT 20;
